apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui
  namespace: sre-monitoring
  labels:
    app: angular-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-ui
  template:
    metadata:
      labels:
        app: angular-ui
    spec:
      imagePullSecrets:
      - name: my-docker-secret  # Added to authenticate with Docker Hub
      containers:
      - name: angular-ui
        image: vishnuvardhandommeti/angular-ui:latest  # Updated with correct Docker image path
        imagePullPolicy: Always  # Ensures the latest image is pulled
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
