apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: sre-monitoring
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: my-docker-secret  # Added to authenticate with Docker Hub
      containers:
      - name: flask-api
        image: vishnuvardhandommeti/flask-api:latest  # Updated with correct Docker image path
        imagePullPolicy: Always  # Ensures the latest image is pulled
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
